= RoboCupJunior OnStage Entry Score Sheets 2025
{docdate}
:toc: left
:sectanchors:
:sectlinks:
:xrefstyle: full
:section-refsig: Section 
:sectnums:

ifdef::basebackend-html[]
++++
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<script src="https://hypothes.is/embed.js" async></script>
++++
endif::basebackend-html[]

:icons: font
:numbered:

These are the official entry score sheets of the _RoboCup Federation_ for the _RoboCupJunior_ (RCJ) OnStage events in 2025.

*The International Original score sheets (in English) have priority over [.underline]#any# translations.*

Major changes from the previous years OnStage score sheets are written in *[red]#red#*.

*Teams should make sure to review _ALL_ pages of these score sheets.* The score sheets have been changed to deepen and broaden the educational benefits of competing in RoboCupJunior. It focuses on the evolving technologies available in our time.

*The rules, score sheets, and all forms of documentation can be downloaded from the official RoboCupJunior website* (https://junior.robocup.org). Each team has a responsibility to verify the latest version of these documents prior to the competition, as changes may be made at any moment. Teams are encouraged to study all documents in detail.

[discrete]
== RoboCupJunior Forum

For inquiries and questions about the score sheets or competition updates, the *Official RoboCupJunior forum* (https://junior.forum.robocup.org/) can be used to contact the OnStage League Committee. All official communication from the committee will be published here before and during the competition season.

[discrete]
== RoboCupJunior OnStage Community Website

Ressources for participating in the OnStage league can be found on the OnStage community website: https://robocup-junior.github.io/onstage

[discrete]
== RoboCupJunior OnStage YouTube channel

Examples of good performances and documentation can be found on the *Official RoboCupJunior OnStage YouTube channel* (https://www.youtube.com/@rcjonstage).